language: node_js
node_js:
- '8'
services:
- postgresql
before_script:
- psql -c 'create database who_are_you_tests;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: x7P+5m0x32/epcFS8EjIJwb9Som0ig+pkISSpmtFEQFKppT+IOANdhpG/THkrflQ70x9bhnLRbOtGZWG0diTGP5S4wsOEnKXI1jBvxL7BO02Z8H7UKrevL+9Lx+fDVUA4vb9WBXhhHhmcnStxkgkXjtMWhyCZodDziZ9S+NzK3VSqg0CSqekW3Ttd40j3+8ORxlpLgXOjzCnCG91u7GHaBOOAjRVk5nTOsx7bhXlFdSnyH2aYbknLP5CwkPH51p9Gf5MQ1Lngw/fQTV512mOOtmrBNePjybLzu+HtOAqCTnHSFkaeg1nIl6RXW68DXG23A3G7Ifwen+TW5BYEFBxwSCr2vi1TyseNUG5jtV3Yp5ypmj0KoZXtlQMxSPzn6kq44vhw2z0O7RV8xbfzW4tZ95F15AMw9GN+KFoTt9KHN7YLCKnHImly6MmC36XmaT7YxogFnI/hvtgfRN17B0K+V3PKGEL8KBzvYz78kx5Y9mH72H35/IdrtEZLOzgxW4qGPbBEnPDde1qtPciJ0OSo8zjsjXQ91VhLYcM51ef+f/riuc/l7BgcUIBge6mJ+PmCv01OpqWbEw9GG70IX4+naAf52ZOw5TY8fYJbULE+kFzSF2C2L4U27JjbwDKgPSVXg0CUmHvqQrawFPGo5odTrvTGVHCzKW0P7YaZiHZppM=
  app: who-were-you
  skip_cleanup: true
